name: push360_sdk
description: Push360 SDK - независимый сервис push-уведомлений для Flutter
version: 1.0.0
homepage: https://push360.ru

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  web_socket_channel: ^2.4.0
  shared_preferences: ^2.2.0
  flutter_local_notifications: ^16.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
